server:
  port: 8002
spring:
  application:
    name: provider-ticket
eureka:
  instance:
    instance-id:  provider-ticket8002  #自定义服务名称信息
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

