server:
  port: 3344

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          #          skipSslValidation: true # 跳过ssl认证
          uri: https://github.com/cs4224485/springcloud-config.git
          ### 搜索目录
          search-paths:
            - springcloud-config
          force-pull: true
          username: cs4224485
          password: cs1993413
      ### 读取分支
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka




#暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: "*"