spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.108:3306/jdbc
    driver-class-name: com.mysql.jdbc.Driver
    schema:
      - classpath:department.sql
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true

  mybatis:
    config-location: classpath:mybatis/mybatis-config.xml \u6307\u5B9A\u5168\u5C40\u914D\u7F6E\u6587\u4EF6\u7684\u4F4D\u7F6E
    mapper-locations: classpath:mybatis/mapper/*.xml  \u6307\u5B9Asql\u6620\u5C04\u6587\u4EF6\u4F4D\u7F6E
